settings:
  book-title: "Punishments"
  book-author: "FlyNeXx"

punishments:

  hacking:
    name: "Hacking"
    command: "jail %player% 3d Hacking"

  spamming:
    name: "Spamming"
    command: "mute %player% 3h Spamming"

  swearing:
    name: "Swearing"
    command: "mute %player% 7h Swearing"

  disrespect:
    name: "Disrespect"
    command: "mute %player% 4h Disrespect"

  advertising:
    name: "Advertising"
    command: "mute %player% 14d Advertising"

  voice:
    name: "Voice Changer"
    command: "ban %player% 4d Voice Changer"

  flooding:
    name: "Flooding"
    command: "banip %player% 18d Flooding"
