settings:
  book-title: "&4Punishments"
  book-author: "FlyNeXx"

  announcement: "&4&lPunishment &8┃ &f%player% &7was punished with &c%punishment% &7for &e%duration%"

punishments:

  "1":
    name: "&cHacking"
    description: "&7Fly/KillAura/Reach"
    type: "JAIL"
    duration: "3 days"
    command: "jail %player% 3d Hacking"

  "2":
    name: "&cSpamming"
    description: "&7Spamming"
    type: "MUTE"
    duration: "3 hours"
    command: "mute %player% 3h Spamming"

  "3":
    name: "&cSwearing"
    description: "&7Swearing"
    type: "MUTE"
    duration: "7 hours"
    command: "mute %player% 7h Swearing"

  "4":
    name: "&cDisrespect"
    description: "&7Disrespect"
    type: "MUTE"
    duration: "4 hours"
    command: "mute %player% 4h Disrespect"

  "5":
    name: "&cAdvertising"
    description: "&7Advertising"
    type: "MUTE"
    duration: "14 days"
    command: "mute %player% 14d Advertising"

  "6":
    name: "&cVoice Changer/abuse/resonance"
    description: "&7Voice Changer/abuse/resonance"
    type: "BAN"
    duration: "4 days"
    command: "ban %player% 4d Voice"

  "7":
    name: "&cFlooding"
    description: "&7Bot/Ddos/Crashing"
    type: "BAN-IP"
    duration: "18 days"
    command: "banip %player% 18d Flooding"
