punishments:
  fly:
    name: "Fly"
    duration: "3 days"
    reason: "Using Fly"
    command: "jail %player% %duration%"

  kill-aura:
    name: "KillAura"
    duration: "7 days"
    reason: "Using KillAura"
    command: "jail %player% %duration%"

  spam:
    name: "Spamming"
    duration: "3 hours"
    reason: "Chat Spam"
    command: "mute %player% %duration%"
