name: PunishmentsBook
version: 2.0.0
main: com.flynexx.punishments.PunishmentsBook
author: FlyNeXx
commands:
  pm:
    description: Opens the punishment page
    usage: /pm <player>
    permission: punishmentsbook.use
  pmapply:
    description: Executes a punishment
    usage: /pmapply <player> <punishment>
    permission: punishmentsbook.use
permissions:
  punishmentsbook.use:
    default: op
